version: '3.9'

services:
  db:
    container_name: todo-db
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5050:5432
  backend:
    container_name: todo-nestjs
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_HOST="todo-db"
  # frontend:
  #   container_name: todo-angular
  #   build:
  #     context: ./frontend
  #   depends_on:
  #     - db
  #     - backend
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'

volumes:
  pgdata:
    driver: local